### ISSUE TITLE
Failed to load index.html

### ISSUE THREAD

**Issue by hosnar** [BroJenuel/vue-3-vite-electron-typescript#1]
Hi.

I've cloned this project and tried to run it with yarn start, but i get this error `Failed to load URL: vue-3-vite-electron-typescript-main/dist/index.html with error: ERR_FILE_NOT_FOUND`. There is not `index.html`file in dist folder. What am i doing wrong?

Thank you

**Comment by JenuelDev** [comment]
Go to this file: `Electron\config.ts`

and change the value to true.

if your deploying, change the value to false. :)
